export const registrationBranchOptions = [
  { value: "CSE", label: "Computer Science and Engineering (CSE)" },
  { value: "CSE-CS", label: "Computer Science and Engineering (Cyber Security)" },
  { value: "ISE", label: "Information Science and Engineering (ISE)" },
  { value: "AIML", label: "Artificial Intelligence and Machine Learning (AIML)" },
  { value: "AIDS", label: "Artificial Intelligence and Data Science (AIDS)" },
  { value: "ECE", label: "Electronics and Communication Engineering (ECE)" },
  { value: "VLSI", label: "Electronics Engineering (VLSI Design & Technology)" },
  { value: "ACT", label: "Electronics & Communication (ACT)" },
  { value: "EEE", label: "Electrical and Electronics Engineering (EEE)" },
  { value: "ME", label: "Mechanical Engineering (ME)" },
  { value: "CV", label: "Civil Engineering (CV)" },
  { value: "BT", label: "Biotechnology (BT)" },
  { value: "CC", label: "Computer Communication Engineering (CCE)" },
  { value: "RAI", label: "Robotics and Artificial Intelligence (RAI)" },
  { value: "CSE-FSD", label: "Computer Science (Full Stack Development) (CSE-FSD)" },
] as const;
